src/commands/deploy.rs
src/main.rs
src/manifest.rs
src/opts.rs

More updates with latest changes to Spin

Add `manifest` module and update `deploy.rs`

---

.github/workflows/build.yml
.github/workflows/release.yml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

Fix `cargo vet` workflow by running `cargo vet init`. Also, ignore running actions on certain cases.

Initialize cargo vet

---

Cargo.lock
Cargo.toml
build.rs
src/main.rs

Add commit sha and date to version

---

src/commands/deploy.rs
src/commands/variables.rs

Fixes #35.
At the moment, this _blocks_ deployment if any required variables are not defined.  This could be reduced to a warning, or we could drop into an interactive session that prompts for the missing variable values - reviewers please share what you think is right!
Because variables may have been defined during a previous deployment, the validator checks what variables are already defined in the cloud.  If an error occurs during this check, the validator currently adopts the principle of cheery optimism: it lets the user know that it couldn't check, but allows the deployment to continue.  Again, reviewers' opinions on whether this is the right thing would be welcome!

Validate application variables are set before deploy

---

src/commands/deploy.rs

Do not deploy SQLite apps to cloud

---

src/commands/sqlite.rs

This avoids the prompt if the database doesn't exist.

Check for existence of database before confirming deletion

---

.github/workflows/release.yml

Continuation of #51 - forgot the manifest file.

Overwrite the plugin manifest

---

Cargo.lock
Cargo.toml

We'll want to release a new version of the plugin that includes all the sqlite related goodness. 
Marking this as a draft until we decide when to do this.

Update the version to 0.1.2

---

Cargo.lock
Cargo.toml

Update spin deps

---

src/commands/deploy.rs

Allow non-default SQL database labels in application manifests

---

src/commands/deploy.rs

fix(sqlite): handle duplicate labels in an app manifest

---

Cargo.lock
Cargo.toml
src/commands/deploy.rs

I'm not sure how to test this @vdice - was your test just to deploy the Fermyon web site?

Update to OCI crate that always inlines

---

src/commands/link.rs
src/commands/sqlite.rs
src/main.rs

tempora mutantur, et nos mutamur in illis

Update SQLite naming

---

Cargo.lock
Cargo.toml
src/commands/deploy.rs

look at all that beautiful red ink in Cargo.lock just look at it

Break spurious dependency on wasmtime

---

Cargo.lock
Cargo.toml
spin-pluginify.toml

Bump version to 0.5.0

---

src/commands/apps.rs
src/commands/deploy.rs
src/commands/link.rs
src/commands/login.rs
src/commands/logs.rs
src/commands/sqlite.rs
src/commands/variables.rs

hide environment-name argument

---

src/commands/apps.rs
src/commands/link.rs
src/commands/mod.rs
src/commands/variables.rs

chore(commands): share CommonArgs struct among commands

---

src/commands/login.rs
src/main.rs

Add logout command

---

src/commands/link.rs

fix(KV): update unlink kv command to match link kv command

---

.github/workflows/release.yml

Such is the life of CI automation/testing

one more download-artifact fix, I promise

---

Cargo.lock
Cargo.toml

If anyone fancies a nice easy review with no maddening redirects

Bump version to 0.11 for release

---

.github/workflows/build.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
src/commands/deploy.rs
src/commands/mod.rs

Notably pulls in [spinframework/spin#3206](https://github.com/spinframework/spin/pull/3206)

Update Spin dep
