README.md
crates/cloud/src/client.rs
src/commands/deploy.rs
src/commands/mod.rs
src/commands/variables.rs
src/main.rs
src/opts.rs

- Draft because i am not sure if we want to wait to merge this once we flip this feature on and whether the cloud plugin will come before config vars
- Moves most of the body of the DeployCommand's `run` function into a sharable `login_connection` function that will likely be used by most subcommands.
- Identifies an app by app manifest `name`
App with the following manifest:
```toml
spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "variables-plugin"
trigger = { type = "http", base = "/" }
version = "1.0.0"
[variables]
host = {required = true}
[[component]]
id = "hello"
source = "target/wasm32-wasi/release/http_rust.wasm"
description = "A simple component that returns hello." …
```

Add `--variables` deploy flag and `variables` subcommand

---

.plugin-manifests/generate-manifest.sh

This is a hacky solution, for the time being, we need a better way to get the version number from `Cargo.toml`
closes #13

fix bash script to get proper version from Cargo.toml for manifests

---

Cargo.lock
Cargo.toml
crates/cloud/Cargo.toml
crates/cloud/src/client.rs
src/commands/deploy.rs
src/commands/variables.rs
src/main.rs
src/opts.rs

Adds `list` and `delete` subcommands to the `variables` CLI
Also, hides the `variables` subcommand and `--variable` deploy flag. Can unhide when we release the feature

Add Variables subcommands for listing and deleting variables

---

.plugin-manifests/generate-manifest.sh
src/commands/deploy.rs
src/commands/variables.rs

In `spin --help`, the `cloud` command has the help text "Commands for publishing applications to the Fermyon Cloud."  This seems like a good description for the plugin too, and will avoid the help text changing after installation if https://github.com/fermyon/spin/pull/1560 gets implemented.

Make plugin manifest description consistent with Spin command description

---

src/main.rs

closes fermyon/spin#1601 by naming the binary Spin even if invoked separately
```sh
$ cloud --help
spin-cloud 0.1.1
Fermyon Engineering <engineering@fermyon.com>
USAGE:
spin cloud <SUBCOMMAND>
OPTIONS:
-h, --help       Print help information
-V, --version    Print version information
SUBCOMMANDS:
deploy       Package and upload an application to the Fermyon Cloud
help         Print this message or the help of the given subcommand(s)
login        Login to Fermyon Cloud
variables    Manage Spin application variables
```

Update CLI to set binary name to Spin

---

src/commands/login.rs

There is no way to login with anything other than GitHub or a token.
This commit removes the prompt when attempting to login with a local URL.

Remove login prompt with local URL

---

Cargo.lock
Cargo.toml
crates/cloud/Cargo.toml
crates/cloud/src/client.rs
src/commands/deploy.rs
src/commands/mod.rs
src/commands/sql.rs
src/commands/sqlite.rs
src/commands/variables.rs
src/main.rs

Looks at an apps' requested `sqlite_databases` and creates a default database for the app if one does not exist.
Also contains other `sqlite` subcommands for listing and deleting databases
Depends on https://github.com/fermyon/cloud-openapi/pull/3

`sqlite` commands

---

src/commands/sqlite.rs

When deleting a sqlite database the prompt currently looks like:
[spin(HEAD)] $ spin cloud sqlite delete nonsense
The action is irreversible. Please type "nonsense" for confirmation.: {cursor here}
The full-stop followed by the colon is a little weird, so drop the full-stop from the prompt to get:
[spin(HEAD)] $ spin cloud sqlite delete nonsense
The action is irreversible. Please type "nonsense" for confirmation: {cursor here}

sqlite delete: remove extra punctuation

---

Cargo.lock
Cargo.toml
src/commands/sqlite.rs

This adds a header to the list of running `cloud-plugin sqlite list`. This is particularly helpful when there are no databases as it otherwise just prints nothing.

Add a header to the databases list output

---

Cargo.lock
Cargo.toml
crates/cloud/Cargo.toml
crates/cloud/src/client.rs
src/commands/deploy.rs
src/commands/mod.rs
src/commands/sqlite.rs
src/commands/variables.rs

Adds the boiler plate code for calling (as of yet non-existent) endpoint in nimbus for executing SQL.

Add execute sql boiler impl

---

.github/workflows/release.yml

@karthik2804 mentioned that the release workflow may fail if more than one runs at a time, due to the `canary` GH release deletion/recreation.  This PR prevents concurrent runs.
May fix or help https://github.com/fermyon/cloud-plugin/issues/39

ci(release.yml): ensure workflow runs sequentially

---

.github/workflows/build.yml
.github/workflows/release.yml

- remove use of actions-rs actions (see also https://github.com/fermyon/spin/pull/1697)
- bump ncipollo/release-action
- use GITHUB_OUTPUT env for outputs
Closes https://github.com/fermyon/cloud-plugin/issues/61

ci(.github): address deprecation warnings

---

.github/workflows/release.yml

Previously, tags weren't actually fetched, throwing off the `canaryExists` logic.
Interestingly, tags still won't be fetched when `fetch-depth` is > 0 (as is the default, being 1), even when toggling `fetch-tags: true` on the [checkout](https://github.com/actions/checkout) action.  (See https://github.com/actions/checkout/issues/701).
Therefore, I just add a `git fetch --prune --unshallow --tags` to start the step.  (Prefer not to set `fetch-depth` to 0 and thus fetch all git history.)
~Depends on https://github.com/fermyon/cloud-plugin/pull/64 (will convert from Draft once merged)~

ci(release.yml): fetch tags to fix canaryExists logic

---

crates/cloud/src/client.rs

update user agent to include spin version

---

crates/cloud/src/client.rs
src/commands/apps.rs
src/commands/deploy.rs
src/commands/login.rs
src/commands/mod.rs
src/commands/variables.rs
src/main.rs
src/opts.rs

This PR adds a new top-level command `apps` that further has `list` and `delete` subcommands. 
fixes #9
fixes #40

add apps subcommand that allows to list and delete apps

---

src/commands/deploy.rs

+ bails if self is included and tells user that feature is not yet supported in cloud
https://github.com/fermyon/spin/pull/1710

add validation for self in allowed_http_hosts

---

.gitignore
README.md
spin-pluginify.toml

Proposal for fixing #36.
Note this does _not_ change CI, so I haven't worried about how to sync the version or maintain the compatibility declaration.  Those would be good to think about as `pluginify` features if people find this useful.

Simplify local dev loop

---

src/commands/sqlite.rs
src/main.rs

Use feature name in `sqlite` CLI

Use "NoOps SQL" feature name in sqlite CLI

---

.github/workflows/release.yml
.plugin-manifests/generate-manifest.sh

* Update the generate-manifest.sh script to use a `REPO_OWNER` env var (or default to `fermyon` if not provided)
* Enables automation for publishing release plugin manifests on forks eg https://github.com/vdice/cloud-plugin/actions/runs/6088260640

ci(*): use REPO_OWNER env in generate-manifest.sh

---

Cargo.lock
Cargo.toml
spin-pluginify.toml

Bumps this plugin version to 0.2.0 in anticipation of a release of the same version.

chore(*): bump plugin version to 0.2.0

---

crates/cloud/src/mocks.rs
src/commands/deploy.rs
src/commands/link.rs
src/commands/sqlite.rs

Users expect to interact with app name rather than app ID. In order to output app names for `spin cloud sqlite list` commands, we should add app name to the `AppLabel` struct.

Add app name to AppLabel

---

.github/workflows/release.yml

Closes https://github.com/fermyon/cloud-plugin/issues/84
Run on fork: https://github.com/vdice/cloud-plugin/actions/runs/6190247031

ci(release.yml): only recreate canary once all artifacts are ready to upload

---

.github/workflows/release.yml

Pins CI runner version so as to produce compatible builds.

ci(release): pin ubuntu runners to 20.04

---

.github/workflows/build.yml
.github/workflows/release.yml

CI updates to mirror what was bumped in Spin in the v1.4.2->v1.5.0 timeframe (eg https://github.com/fermyon/spin/pull/1731 and https://github.com/fermyon/spin/pull/1741)
Prerequisite PR in anticipation of revving the spin crates to v1.5.0 in https://github.com/fermyon/cloud-plugin/pull/57

ci(.github): bump rust to 1.71; add +fp16 rustc flag for linux/aarch64 build

---

src/main.rs

Fixes #83.
As noted on that issue, before merging this we should understand the intent behind having the `propagate_version` flag there in the first place.  @kate-goldenring `git blame` has your name on the commit, though I think several people contributed to that first cut - do you know why this was set?
Before:
```
$ spin cloud variables -V
spin-cloud-variables 0.2.0 (78c325a 2023-09-14)
```
After:
```
$ spin cloud variables -V
error: Found argument '-V' which wasn't expected, or isn't valid in this context
If you tried to supply `-V` as a value rather than a flag, use `-- -V`
USAGE:
spin cloud variables <SUBCOMMAND>
For more information try --help
$ spin cloud -V
spin-cloud 0.2.0 (78c325a 2023-09-14)
```

Do not offer --version on subcommands

---

crates/cloud/src/client.rs
src/commands/apps.rs

This PR adds a get subcommand to apps to allow for getting details about an app. It helps with getting the Base URL of apps quickly without having to open up the cloud UI.

Add get app subcommand to get app details

---

src/commands/apps.rs
src/commands/sqlite.rs

This PR does two things (in two separate commits, as all of this is likely to be subjective).  It is purely a refactoring and should not change any existing behaviour.  (Okay, okay.  In the vanishingly implausible cases where an app has an empty URL, the print behaviour changes slightly.  Truth in advertising.)
1. It splits the `apps` and `sqlite` command handlers into subcommand handlers.  This removes two levels of indentation from the actual command handling code, to my eye making it easier to track, and creates some visual separation between the subcommand blocks.
2. It streamlines (in my opinion of course!) the rendering part of the `spin cloud apps info` command by moving some logic into helper functions, and teasing apart the "what do we want to print" from the actual printing.  I …

Split up some large command handlers

---

Cargo.lock
Cargo.toml
src/commands/deploy.rs
src/main.rs
src/opts.rs

Also includes:
- Bumping spin crates to v1.5.0
- Removing bindle-related code
- Sanitizing app name and version per OCI reference restrictions
- Setting SPIN_OCI_SKIP_INLINED_FILES to ensure empty/small files are inlined
(Replaces https://github.com/fermyon/cloud-plugin/pull/57 which proved too onerous to rebase; we have the commits in that branch if we need to look back in history, though most were chore-related/incremental)

Update deploy to use OCI as distribution mechanism

---

src/main.rs

Allows `spin cloud app ...` usage.

feat(main.rs): add app alias for apps command

---

src/commands/deploy.rs
src/main.rs
src/spin.rs

Fixes #95.
Happy path:
```
ivan@hecate:~/testing/hello3$ spin deploy --build
Building component hello3 with `cargo build --target wasm32-wasi --release`
Compiling hello3 v0.1.0 (/home/ivan/testing/hello3)
Finished release [optimized] target(s) in 1.19s
Finished building all Spin components
Uploading hello3 version 0.1.0+r73691dd...
Deploying...
Waiting for application to become ready.......... ready
Available Routes:
hello3: https://hello3-prfvru2v.fermyon.app (wildcard)
```
Sad path:
```
ivan@hecate:~/testing/hello3$ spin deploy --build
Building component hello3 with `cargo build --target wasm32-wasi --release`
Compiling hello3 v0.1.0 (/home/ivan/testing/hello3)
error[E0425]: cannot find function, tuple struct or tuple variant `Sum` in this scope
--> src/lib.rs:12:15
|
12 | …
```

Option to force build before deploy

---

Cargo.lock
Cargo.toml

Bumps to current HEAD commit of Spin, particularly to get https://github.com/fermyon/spin/commit/d041cc0470c39a341de7b709e7cab5e7d5a011ef
Closes https://github.com/fermyon/cloud-plugin/issues/101

chore(Cargo.toml): bump spin crates

---

src/commands/sqlite.rs

Before fix:
```sh
$ spin cloud sqlite list
+------+-------+----------+
| App  | Label | Database |
+=========================+
| todo | hello | mydb     |
+------+-------+----------+
```
After fix
```sh
$ spin cloud sqlite list
+------+---------+--------------------+
| App  | Label   | Database           |
+=====================================+
| todo | default | brilliant-kangaroo |
|------+---------+--------------------|
| todo | hello   | mydb               |
+------+---------+--------------------+
```

Fix database printing to show all of an app's databases

---

src/commands/deploy.rs

There is a bug in current `main` where if:
* An app already exists in Cloud
* The app declares a SQLite database
* The SQLite database is already fulfilled
then it mistakenly returns "user cancelled" from the database linking function, causing the deployment to silently nope out.  Basically apps with databases will fail to upgrade without reporting any error.
Before:
```
ivan@hecate:~/testing/sqlmadness$ spin cloud deploy
Uploading sqlmadness version 0.1.0-rcfcbd78 to Fermyon Cloud...
Deploying...
```
With this change:
```
ivan@hecate:~/testing/sqlmadness$ spin cloud deploy
Uploading sqlmadness version 0.1.0-r0de736f to Fermyon Cloud...
Deploying...
Waiting for application to become ready........ ready
Available Routes:
sqlmadness: https://sqlmadness-ax7chkqb.fermyon.app (wildcard)
```
I …

Fix silent cancellation when app db already fulfilled

---

Cargo.lock
Cargo.toml
src/commands/deploy.rs
src/opts.rs

This is VERY VERY DRAFT.  The code needs a lot of tidying ~; it doesn't currently validate OCI apps (for unsatisfied variables, nondefault stores, etc.); and I have broken the route printing~.  And probably other stuff too.  But it worked, on my machine, at least once, so :shipit: 
**NOTES:**
* The download from the source registry currently always requires HTTPS and uses the default Spin cache. We could add `deploy` options for these if we wanted to - easy to implement, but more for users to understand.

Deploy from an OCI reference

---

release-process.md

Add a checklist for releasing the plugin.
Apparently [some of us](https://github.com/fermyon/cloud-plugin/pull/111) need the reminder 😂

docs(release): add release-process.md

---

Cargo.lock
Cargo.toml

😬 I forgot to bump the version for this plugin prior to last week's release.
We can either follow up with a 0.3.1 version bump + release soon after (to get correctly-versioned plugin binaries) or wait and continue with a 0.4.0 release with the features/fixes that have landed on main since.

chore(Cargo.toml): bump version to 0.3.0

---

src/commands/sqlite.rs

Simplifies handling of app printing. The only semantic difference is that if there is a bug and more than one link is returned for the same database, app, label trio, the previous implementation would not print it out, but this will. Such a situation is clearly a bug, and I think the simpler implementation is preferable.

Small clean up in app printing

---

src/commands/link.rs
src/commands/sqlite.rs

Small CLI description updates that should go in before the next release

Fix SQL and link subcommand descriptions

---

src/commands/sqlite.rs

Takes a similar approach as `spin templates list` and provides an option of listing databases as JSON
Example output:
```sh
[
{
"database": "brilliant-kangaroo",
"links": [
{
"label": "default",
"app": "todo"
}
]
},
{
"database": "mydb",
"links": [
{
"label": "hello",
"app": "todo"
},
{
"label": "foo",
"app": "bar"
}
]
}
]
```

Support outputting a list of databases as JSON

---

Cargo.lock
Cargo.toml
crates/cloud/src/client.rs
src/commands/sqlite.rs

Draft until the API is available in Fermyon Cloud and openapi clients have been generated
depends on https://github.com/fermyon/cloud-openapi/pull/7

Support renaming SQL databases

---

release-process.md

Currently the plugin version is also tracked in the spin-pluginify.toml file, so adding a mention to keep in sync.
We could also entertain using some other version string in the file so that we aren't obligated to keep it in sync... or PR a feature to the upstream repo wherein pluginify might auto-detect the version :)  cc @itowlson

docs(release-process.md): bump version in spin-pluginify.toml as well

---

src/commands/sqlite.rs

Make it easier to see more with less. 
From
```sh
$ spin cloud sqlite list
+----------+---------+----------+
| App      | Label   | Database |
+===============================+
| boo-todo | default | newdb    |
|----------+---------+----------|
| boo-todo | bar     | newname  |
+----------+---------+----------+
```
To
```sh
$ spin cloud sqlite list
+-------------------------------+
| App        Label     Database |
+===============================+
| boo-todo   default   newdb    |
| boo-todo   bar       newname  |
+-------------------------------+
```

Condense SQL databases list output

---

src/commands/link.rs

Currently, to change the database linked to an app with a label, you have to unlink and then link.
```sh
$ spin cloud link sqlite --app boo-todo --database newname default
Error: Database "newdb" is already linked to app "boo-todo" with label "default"
$ spin cloud unlink sqlite --app boo-todo default
Database 'newdb' no longer linked to app boo-todo
$ spin cloud link sqlite --app boo-todo --database newname default
Database 'newname' is now linked to app 'boo-todo' with the label 'default'
```
With change, do not need to unlink to change a link.
```sh
$ spin cloud link sqlite --app boo-todo --database newname default
Database "newdb" is already linked to app "boo-todo" with label "default". Link to database "newname" instead? yes
Database "newname" is now linked to app "boo-todo" with …
```

Enable updating a link with `spin cloud link sqlite`

---

Cargo.lock
Cargo.toml
spin-pluginify.toml

Bumping the plugin version in anticipation of the next 0.4.0 release.
Release will include: https://github.com/fermyon/cloud-plugin/compare/v0.3.0...main

chore(Cargo.toml): bump to 0.4.0

---

Cargo.lock
Cargo.toml
crates/cloud/Cargo.toml
crates/cloud/src/client.rs
crates/cloud/src/client_interface.rs
crates/cloud/src/lib.rs
src/commands/apps.rs
src/commands/deploy.rs
src/commands/link.rs
src/commands/login.rs
src/commands/mod.rs
src/commands/sqlite.rs
src/commands/variables.rs

This is a proposed approach to increasing our unit tests in this repository by making the `CloudClient` mockable. It uses the `mockall` crate by having the `CloudClient` implement a `CloudClientInterface` that can be mocked. Also has a few tests for examples.
Pros to this approach:
- Can add more tests to ensure user input is erroring as expected
- Can add tests to ensure we are handling the data returned from the cloud 
Cons:
- As @itowlson [mentions](https://github.com/fermyon/cloud-plugin/issues/124#issuecomment-1749708109), with mocks, tests can be verbose and potentially summed up to "we can confirm it makes this series of API calls but 🤷"
- Requires passing the client as an argument to any testable functions
(I'm sure there are other pros and cons i am forgetting)
fixes …

Framework for testing interactions with `CloudClient`

---

src/commands/deploy.rs
src/main.rs
src/opts.rs

~Exterminates~ Fixes #41.
Tested redeploying an application without changing its version and `deploy` correctly waited for the new version to become ready before reporting completion.

Remove deploy --buildinfo and --no-buildinfo flags

---

src/commands/deploy.rs
src/commands/sqlite.rs

Fixes #70.
I noticed there was an existing `database_has_link` function but it needs a UUID.  Should I be fetching one in the app case?  I couldn't see how it would help (because the UUID derives from the name anyway), but am probably missing something!

`spin cloud sqlite execute` by label

---

crates/cloud/src/client_interface.rs
crates/cloud/src/cloud_client_extensions.rs
crates/cloud/src/lib.rs
src/commands/apps.rs
src/commands/deploy.rs
src/commands/mod.rs
src/opts.rs

This is a pure refactor - no behaviour changes.  (Unless I messed up.)
While working on some reorganisation of the `deploy` module, I noticed we had some instance methods that didn't use `self` and in fact seemed more concerned with the `CloudClient` than with the `DeployCommand`.  For me it felt more readable to pull them out as extension methods on the `CloudClientInterface`.  (My main interest was in moving code out of `DeployCommand`, which could be done without traitifying.  But this felt nicer.)
I also noticed that `commands::get_app_id_cloud` and `DeployCommand::try_get_app_id_cloud` did the same thing (modulo one `anyhow::Context`), so unified them.
I removed the `_cloud` suffixes which were inherited from earlier Spin code where they had to be distinguished from Platform …

Move some cloud functions to an extension

---

Cargo.lock
Cargo.toml

Bump spin crates to https://github.com/fermyon/spin/commit/54c4d83987f0519ef885b532d577845443d4d61b to get fix for https://github.com/fermyon/spin/issues/1787 and related commits.
Full diff: https://github.com/fermyon/spin/compare/0306346...54c4d83

chore(Cargo.toml): bump spin crates to v1.6 branch revision

---

Cargo.lock
Cargo.toml
src/commands/deploy.rs

Backports of https://github.com/fermyon/cloud-plugin/commit/25fcb39b6fa339220e6b8c4a663679667c376c11 and https://github.com/fermyon/cloud-plugin/commit/7a813317a5dae6614b880ce72e6666641872d0e2 on top of v0.4.0 in prep for a[ forthcoming 0.4.1 release](https://github.com/fermyon/cloud-plugin/pull/137)

Backport 133 to v0.4

---

Cargo.lock
Cargo.toml

Version bump to 0.4.1 after https://github.com/fermyon/cloud-plugin/pull/136 is in.
Diff: https://github.com/fermyon/cloud-plugin/compare/v0.4.0...v0.4
~~Depends on https://github.com/fermyon/cloud-plugin/pull/136 (will rebase afterwards)~~ done

chore(Cargo.toml): bump to 0.4.1

---

spin-pluginify.toml

Missed in https://github.com/fermyon/cloud-plugin/pull/137

chore(spin-pluginify.toml): bump to 0.4.1

---

Cargo.lock
Cargo.toml
src/commands/deploy.rs
testdata/based_v1.toml
testdata/based_v2.toml
testdata/dummy.not-actually-wasm
testdata/unbased_v1.toml
testdata/unbased_v2.toml

For when https://github.com/fermyon/spin/pull/1780 lands.  The new load path moves all of the LockedApp fiddliness into the Spin loader, so we pretty much don't have to do anything to consume it any more!
The Spin crate references will need to be set back to the Fermyon repo at this point - this points them at @lann's branch just for development.

Manifest v2 support

---

Cargo.lock
Cargo.toml
crates/cloud/src/client.rs
crates/cloud/src/client_interface.rs
src/commands/deploy.rs
src/commands/logs.rs
src/commands/mod.rs
src/main.rs

```
spin-cloud-logs 0.1.2 (b977558 2023-08-11)
Logs fetches app logs from Fermyon Cloud
USAGE:
spin cloud logs [OPTIONS] --app-name <app-name>
OPTIONS:
--app-name <app-name>
App name
--environment-name <environment-name>
Find app to fetch logs for in the Fermyon instance saved under the specified name. If
omitted, Spin looks for app in default unnamed instance [env:
FERMYON_DEPLOYMENT_ENVIRONMENT=]
--follow
Follow logs output
-h, --help
Print help information
--interval <interval>
interval in secs to refresh logs from cloud [default: 5]
--tail <tail>
Number of lines to show from the end of the logs [default: 10]
-V, --version
Print version information
```

add cloud logs command

---

Cargo.lock
Cargo.toml

This updates the Spin crate references to a near-2.0 commit.  This is needed so that deploy can process the latest Manifest 2 changes, specifically `allowed_outbound_hosts`.
Because the latest Spin crates change the OCI format, **this cannot merge until the associated Cloud PR merges** or apps will appear to deploy but never go live.  This is in progress with @vdice.  Once that happens I will test and merge this.

Update to latest Spin crates

---

Cargo.lock
Cargo.toml

Revs to https://github.com/fermyon/spin/commit/d816b512cc541138d489fcbd29ec535b9958f31e

chore(Cargo.toml): bump spin crates to latest v2.0 branch revision

---

Cargo.lock
Cargo.toml
spin-pluginify.toml

Diff is: https://github.com/fermyon/cloud-plugin/compare/v0.5.0...main

chore(*): bump version to 0.5.1

---

src/commands/deploy.rs
src/commands/login.rs
src/commands/mod.rs

Fixes #152.
This shows only "view/manage" if there is a single blanket component, but breaks out the routes display if there are multiple components.  E.g.
```
ivan@hecate:~/testing/dbmadness$ spin cloud deploy
Uploading dbmadness version 0.1.0 to Fermyon Cloud...
Deploying...
Waiting for application to become ready.......... ready
View application:   https://dbmadness-hyi1xhfs.fermyon.app/
Manage application: https://cloud.fermyon.com/app/dbmadness
ivan@hecate:~/testing/dbmadness$ spin cloud deploy
Uploading dbmadness version 0.1.0 to Fermyon Cloud...
Deploying...
Waiting for application to become ready.................. ready
View application:   https://dbmadness-hyi1xhfs.fermyon.app/
Routes:
- dbmadness: https://dbmadness-hyi1xhfs.fermyon.app (wildcard)
Absolute madness, you'll laugh, …
```

Tweak route printing

---

src/commands/deploy.rs
src/commands/deploy/database.rs

This is another take on #125 (cf. #126).  It's significantly more complicated than #126, but aims to be more explicit.
I am not delighted with the CLI experience in this initial draft.  This looks like:
```
spin cloud deploy --link sqlite:default=* --link sqlite:monies=finance
```
Here the `sqlite:` prefix says what the label refers to (to allow for K/V or other resource linking in future), and `*` is a magic symbol for "create a new and link that".  This is a lot more verbose than @kate-goldenring's example syntax in https://github.com/fermyon/cloud-plugin/pull/126#issuecomment-1749763854 and perhaps the future-proofing is too speculative, I'm not sure; and of course magic symbols are never great for discoverability.
That said, I'm optimistic about the principle of using a strategy …

Non interactive databases take two

---

crates/cloud/src/client.rs
crates/cloud/src/client_interface.rs
crates/cloud/src/cloud_client_extensions.rs
src/commands/deploy.rs

New updates to the Fermyon Cloud API made the calls to `POST /api/channels` and `PATCH /api/channels` redundant as the active revision is calculated based on the app's list of revisions. A client now only has to call `create_app` followed by `add_revision` to trigger a deploy to production. On follow-up deploys, only a call to `add_revision` is necessary.

`spin cloud deploy`: Drop calls to create/update channel

---

src/commands/deploy.rs

This allows the Spin CLI to receive more contextual errors which helps with debugging.
Old error format:
```
><> spin deploy
Uploading spin-checklist version 0.1.0 to Fermyon Cloud...
Deploying...
Error: response status code: 404 Not Found
```
New error format:
```
><> spin deploy
Uploading spin-checklist version 0.1.0 to Fermyon Cloud...
Deploying...
Error: Unable to add revision: response status code: 404 Not Found
```

add more context to certain errors

---

Cargo.lock
Cargo.toml
src/commands/deploy.rs

I am currently not able to build main. Rather than debugging the linting issues in spin crates, I figured it's time to bump to latest spin crates.

chore(*): use latest spin crates

---

Cargo.lock
Cargo.toml
crates/cloud/src/client.rs
crates/cloud/src/client_interface.rs
src/commands/key_value.rs
src/commands/link.rs
src/commands/links_output.rs
src/commands/mod.rs
src/commands/sqlite.rs
src/main.rs

DO NOT MERGE until changes are merged in https://github.com/fermyon/cloud-openapi/pull/11
Aims to reuse as much logic and keep error formatting consistent via the `link_utils` module.

Add command for managing key value stores and links

---

src/commands/deploy.rs
src/commands/deploy/resource.rs
src/commands/sqlite.rs

Follow up to https://github.com/fermyon/cloud-plugin/pull/170

chore(links): rename database module to resource

---

src/commands/link.rs

Right now `spin cloud link` does not give a description for the KV subcommand. Also would be ideal to have consistency of `spin cloud link key-value` and `spin cloud key-value`

fix(KV): add description to KV link instruction

---

src/commands/apps.rs

Fixes formatting of description on `apps info`.
```
$ spin cloud apps info new-rust
Warning: You're using a pre-release version of Spin (2.4.0-pre0). This plugin might not be compatible (supported: >=1.3). Continuing anyway.
Name: new-rust
DescriptionMy new Spin app using the Rust SDK
URL: https://new-rust-oar3balb.fermyon.app
```
->
```
$ spin cloud apps info new-rust
Warning: You're using a pre-release version of Spin (2.4.0-pre0). This plugin might not be compatible (supported: >=1.3). Continuing anyway.
Name: new-rust
Description: My new Spin app using the Rust SDK
URL: https://new-rust-oar3balb.fermyon.app
```

fix(apps.rs): fix formatting for description

---

.github/workflows/release.yml

#188 bumped up from upload-artifact v3 to v4, which introduces a significant breaking change: uploads to artifacts are now immutable.
See https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

upload to separate artifacts

---

.github/workflows/release.yml

Unlike the binary artifacts, these artifact names are not used anywhere in the pipeline. It appears to be there just to ensure we upload these objects to an alternative location.
closes #190

use unique names for checksums/plugin manifest

---

src/nouns.txt

There was a whitespace after "boson" in `./src/nouns.txt` which broke key-value store generation upon deployment to cloud

fix: remove whitespace from noun

---

Cargo.lock
Cargo.toml
src/commands/deploy.rs

- Bumps the oci-distribution crate to https://github.com/fermyon/oci-distribution/commit/7e4ce9be9bcd22e78a28f06204931f10c44402ba
- Bumps the spin crates to https://github.com/fermyon/spin/commit/86a58771091c02eaf40b5395a2a6bc711740f038
With these bumps come the following fixes/features, both relevant to `spin cloud deploy`:
- OCI layers for an application are de-duplicated which can help reduce the size of some apps (think: heavy on static assets shared across components; heavy component re-use).  Recall that Fermyon Cloud currently enforces a 100 MB app limit.  Prior to deduplication, some apps would exceed this limit and attempts to deploy would fail as a result. (Ref https://github.com/fermyon/spin/pull/2395)
- Increase the default token expiration timeout when pushing a spin app. …

chore(*): bump oci and spin crates; update usage

---

Cargo.lock
Cargo.toml
spin-pluginify.toml

Bump to 0.9.0 for the intended forthcoming release
[Changelog](https://github.com/fermyon/cloud-plugin/compare/v0.8.0...main)

chore(*): bumps for 0.9.0 release

---

.github/workflows/build.yml
.github/workflows/release.yml

The 0.9.0 mac amd64 binary was actually built on the aarch64 arch since it used the mutable `macos-latest` runner name, which has since migrated to apple silicon.
- Restore mac amd64 builds via pinning runner to macos-13
- Pin mac aarch64 runner to macos-14
Tested on fork: https://github.com/vdice/cloud-plugin/actions/runs/9650833532; amd64 binary now as expected (`Mach-O 64-bit executable x86_64`).
Will cut an 0.9.1 release of the plugin once this is in.

ci(.github): pin macos runner versions; restore amd64 builds via macos-13

---

Cargo.lock
Cargo.toml
spin-pluginify.toml

In anticipation of a 0.9.1 patch release to pull in https://github.com/fermyon/cloud-plugin/pull/205 and fix mac amd64 build

chore(*): 0.9.1 bumps

---

.github/workflows/release.yml

- Only create the GH release after all artifacts are uploaded.  (Previously the first artifact upload to a given release would de facto create said release, while other artifacts were still yet to be built and uploaded.)
Closes https://github.com/fermyon/cloud-plugin/issues/204
Tested on fork:
- [canary](https://github.com/vdice/cloud-plugin/releases/tag/canary) via https://github.com/vdice/cloud-plugin/actions/runs/9653445957
- [semver](https://github.com/vdice/cloud-plugin/releases/tag/v0.0.0-vdice-test) via https://github.com/vdice/cloud-plugin/actions/runs/9653650772

ci(release.yml): create GH release after all artifacts are uploaded

---

src/commands/deploy.rs

The current plugin allows an app to be deployed with duplicate routes.  This fails in Cloud at runtime with a ghost error.  This PR makes it fail deployment.
```
ivan@hestia:~/testing/dup-routes$ spin cloud deploy
Error: This application contains duplicate routes, which are not allowed in Fermyon Cloud.
- Route '/...' appears in components 'dupier-routes' and 'dup-routes'
Learn more at https://developer.fermyon.com/cloud/faq
```
(the FAQ is unhelpful here, but cannot currently be suppressed on a case-by-case basis)

Prevent app with duplicate routes from being deployed to Cloud

---

src/commands/apps.rs
src/commands/apps_output.rs
src/commands/mod.rs

This PR adds the `--format` flag (values `Plain` & `Json`) to the following commands:
- `spin cloud apps list`
- `spin cloud apps info <app_name>`
The enum contains the `Plain` variant (which is also set as default value for both commands) due to backward compatibility reasons.

Add support for formatting output of `cloud apps list` and `cloud apps info`

---

src/commands/logs.rs

Lann spotted this when we were reusing the code in another project.  Backporting!

Fixed minor typo in doc string

---

.github/workflows/release.yml

Bumps the Ubuntu images to 22.04 per the [deprecation of 20.04](https://github.com/actions/runner-images/issues/11101).

chore(.github): bump ubuntu images to 22.04

---

.github/workflows/build.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
crates/cloud/Cargo.toml
src/commands/deploy.rs

Spin now enables specifying whether distributed artifacts are composed or not. This ensures the cloud plugin continues to not compose artifacts.
Ref https://github.com/spinframework/spin/pull/2996

Ensure apps are deployed without composition

---

src/commands/deploy.rs

Fixes #225.
Per discussion there, this now refreshes the token if it is within 5 minutes of expiry.  So we should be safe for deployment operations that last less than 5 minutes, and less likely to suffer mid-operation expiry even on very long-running operations.
Tested by setting the "must have remaining" time to 28 minutes and verifying that it refreshed after 2 minutes.

Deploy: refresh token if close to expiry
